server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: service-clientes
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/clientes/**

            - id: service-equipo
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/equipos/**

            - id: service-servicio
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/servicios/**

            - id: service-orden
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/ordenes/**

            - id: service-voucher
              uri: http://localhost:8085
              predicates:
                - Path=/api/v1/vouchers/**

            - id: service-estadisticas
              uri: http://localhost:8086
              predicates:
                - Path=/api/v1/estadisticas/**

            - id: service-hardware
              uri: http://localhost:8087
              predicates:
                - Path=/api/v1/hardware/**

            - id: service-software
              uri: http://localhost:8088
              predicates:
                - Path=/api/v1/software/**

            - id: service-mantenimiento
              uri: http://localhost:8089
              predicates:
                - Path=/api/v1/mantenimiento/**
            
            - id: service-descuento
              uri: http://localhost:8090
              predicates:
                - Path=/api/v1/descuento/**

springdoc:
  swagger-ui:
    urls:
      - name: Servicio Técnico
        url: /api/v1/servicios/v3/api-docs
      - name: Órdenes de Trabajo
        url: /api/v1/ordenes/v3/api-docs
      - name: Software
        url: /api/v1/software/v3/api-docs
      - name: Mantenimiento
        url: /api/v1/mantenimiento/v3/api-docs
      - name: descuento
        url: /api/v1/descuento/v3/api-docs