spring.application.name=service_orden

server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/pc_orden?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
